apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ticketing.dev
      http:
        paths:
          - path: /api/users/ # Removed regex and fixed path
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 4000
          - path: /api/tickets/ # Removed regex and fixed path
            pathType: Prefix
            backend:
              service:
                name: tickets-srv
                port:
                  number: 4001
          - path: /api/payments/ # Removed regex and fixed path
            pathType: Prefix
            backend:
              service:
                name: payments-srv
                port:
                  number: 4004
          - path: /api/orders/ # Removed regex and fixed path
            pathType: Prefix
            backend:
              service:
                name: orders-srv
                port:
                  number: 4002
          - path: / # Changed root path for general client-srv route
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
